### ISSUE TITLE
Error: Can only call rawCollection on server collections

### ISSUE THREAD

**Issue by santiagopuentep** [jamauro/offline#1] opened 2024-07-20 02:00 UTC
This package is exactly what I was looking for, but I'm getting the following error in my project when creating a collection that works on the client and on the server:

`Error: Can only call rawCollection on server collections`

I'm using `METEOR@2.14`.

I'm not calling `rawCollection` anywhere in my code.

**Comment by jamauro** [comment] 2024-07-20 04:36
Hmm, I'm not able to reproduce this on a fresh project. Can you provide a simple reproduction in a GitHub repo I could take look at? Thanks!

**Comment by jamauro** [comment] 2024-07-25 15:45
This should be fixed in `v0.1.1`. If you run into it again, please re-open the issue.

**Closed as completed by jamauro** 2024-07-25 15:45 UTC
